apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prestashop-ingress
spec:
  rules:
    - host: prestashop.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: prestashop
              servicePort: 80
