apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-pvc
  namespace: prestashop
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
