apiVersion: v1
kind: ConfigMap
metadata:
  name: prestashop-config
  namespace: prestashop
data:
  prestashop_database_user: "admin"
  prestashop_database_name: "mariadb"
  allow_empty_password: "yes"
  prestashop_host: "172.16.203.150"
  prestashop_apache_port_number: "30000"
  mariadb_host: "mariadb"
