kind: PersistentVolume
apiVersion: v1
metadata:
  name: prestashop-pv-volume
  namespace: prestashop
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /tmp/prestashop
