apiVersion: v1
kind: Service
metadata:
  name: prestashop
  namespace: ps
  labels:
    name: prestashop
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 30000
      targetPort: 30000
      nodePort: 30000
  selector:
    app: prestashop
