apiVersion: v1
kind: Service
metadata:
  labels:
    name: mariadb
  name: mariadb
  namespace: apps-ns
spec:
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
